local p = require("sugarpunk.palette")
local cfg = require("sugarpunk.config")

local M = {}

local function hi(group, opts)
    vim.api.nvim_set_hl(0, group, opts)

end

function M.apply()
    local sComm = cfg.style("comments")
    local sKeyw = cfg.style("keywords")
    local sBool = cfg.style("booleans")
    local sFn = cfg.style("functions")
    local sVar = cfg.style("variables")

    -- base
    hi("Normal", { fg = p.slate_light, bg = p.void })
    hi("NormalFloat", { fg = p.slate_light, bg = p.gunmetal })
    hi("NormalNC", { fg = p.slate_light, bg = p.void })
    hi("FloatBorder", { fg = p.slate_light, bg = p.gunmetal })
    hi("FloatTitle", { fg = p.slate_light, bg = p.gunmetal, bold = true })
    hi("Cursor", { fg = p.void, bg = p.electric_blue })
    hi("CursorLine", { bg = p.gunmetal })
    hi("CursorLineNr", { fg = p.electric_blue, bg = p.gunmetal, bold = true })
    hi("CursorColumn", { bg = p.gunmetal })
    hi("ColorColumn", { bg = p.gunmetal })
    hi("LineNr", { fg = p.electric_blue_dim })
    hi("SignColumn", { fg = p.slate_light, bg = p.void })
    hi("FoldColumn", { fg = p.electric_blue_dim, bg = p.void })
    hi("Folded", { fg = p.slate_light, bg = p.gunmetal, italic = true })
    hi("Visual", { bg = p.electric_blue_faint })
    hi("VisualNOS", { bg = p.electric_blue_faint })
    hi("IncSearch", { fg = p.void, bg = p.electric_blue, bold = true })
    hi("Search", { fg = p.void, bg = p.electric_blue_dim })
    hi("MatchParen", { fg = p.electric_blue, bg = p.electric_blue_faint, bold = true })
    hi("StatusLine", { fg = p.slate_light, bg = p.gunmetal })
    hi("StatusLineNC", { fg = p.electric_blue_dim, bg = p.gunmetal })
    hi("WinBar", { fg = p.slate_light, bg = p.gunmetal })
    hi("WinBarNC", { fg = p.electric_blue_dim, bg = p.gunmetal })
    hi("WinSeparator", { fg = p.electric_blue_dim })
    hi("VertSplit", { fg = p.electric_blue_dim })
    hi("TabLine", { fg = p.electric_blue_dim, bg = p.gunmetal })
    hi("TabLineSel", { fg = p.electric_blue, bg = p.void, bold = true })
    hi("TabLineFill", { bg = p.gunmetal })
    hi("Pmenu", { fg = p.slate_light, bg = p.gunmetal })
    hi("PmenuSel", { fg = p.off_white, bg = p.electric_blue_faint })
    hi("PmenuSbar", { bg = p.gunmetal })
    hi("PmenuThumb", { bg = p.electric_blue_dim })
    hi("PmenuKind", { fg = p.chrome_teal, bg = p.gunmetal })
    hi("PmenuKindSel", { fg = p.chrome_teal, bg = p.electric_blue_faint })
    hi("PmenuExtra", { fg = p.electric_blue_dim, bg = p.gunmetal })
    hi("PmenuExtraSel", { fg = p.electric_blue_dim, bg = p.electric_blue_faint })
    hi("NonText", { fg = p.gunmetal })
    hi("SpecialKey", { fg = p.electric_blue_dim })
    hi("Whitespace", { fg = p.gunmetal })
    hi("EndOfBuffer", { fg = p.gunmetal })
    hi("Conceal", { fg = p.electric_blue_dim })
    hi("Title", { fg = p.off_white, bold = true })
    hi("Question", { fg = p.electric_blue })
    hi("MoreMsg", { fg = p.electric_blue })
    hi("ModeMsg", { fg = p.off_white })
    hi("MsgArea", { fg = p.slate_light })
    hi("ErrorMsg", { fg = p.synth_magenta, bg = p.void, bold = true })
    hi("WarningMsg", { fg = p.cyber_orange })
    hi("Directory", { fg = p.electric_blue })
    hi("QuickFixLine", { bg = p.electric_blue_faint })
    hi("WildMenu", { fg = p.void, bg = p.electric_blue, bold = true })
    hi("SpellBad", { undercurl = true, sp = p.synth_magenta })
    hi("SpellCap", { undercurl = true, sp = p.cyber_orange })
    hi("SpellRare", { undercurl = true, sp = p.chrome_teal })
    hi("SpellLocal", { undercurl = true, sp = p.electric_blue })
    hi("Substitute", { fg = p.void, bg = p.cyber_orange })

    -- syntax
    hi("Comment", { fg = p.slate_light, italic = sComm.italic, bold = sComm.bold })
    hi("Constant", { fg = p.synth_magenta })
    hi("String", { fg = p.neon_pink })
    hi("Character", { fg = p.neon_pink })
    hi("Number", { fg = p.aurum_gold })
    hi("Float", { fg = p.aurum_gold })
    hi("Boolean", { fg = p.cyber_orange, italic = sBool.italic, bold = sBool.bold })
    hi("Identifier", { fg = p.matrix_green, italic = sVar.italic, bold = sVar.bold })
    hi("Function", { fg = p.neon_yellow, italic = sFn.italic, bold = sFn.bold })
    hi("Statement", { fg = p.synth_magenta, italic = sKeyw.italic, bold = sKeyw.bold })
    hi("Conditional", { fg = p.cyber_orange, italic = sKeyw.italic, bold = sKeyw.bold })
    hi("Repeat", { fg = p.cyber_orange, italic = sKeyw.italic, bold = sKeyw.bold })
    hi("Label", { fg = p.cyber_orange, italic = sKeyw.italic, bold = sKeyw.bold })
    hi("Operator", { fg = p.cyber_orange })
    hi("Keyword", { fg = p.synth_magenta, italic = sKeyw.italic, bold = sKeyw.bold })
    hi("Exception", { fg = p.cyber_orange, italic = sKeyw.italic, bold = sKeyw.bold })
    hi("PreProc", { fg = p.violet_flux })
    hi("Include", { fg = p.violet_flux })
    hi("Define", { fg = p.violet_flux })
    hi("Macro", { fg = p.matrix_green })
    hi("PreCondit", { fg = p.violet_flux })
    hi("Type", { fg = p.electric_blue })
    hi("StorageClass", { fg = p.cyber_orange })
    hi("Structure", { fg = p.chrome_teal })
    hi("Typedef", { fg = p.chrome_teal })
    hi("Special", { fg = p.cyber_orange })
    hi("SpecialChar", { fg = p.aurum_gold })
    hi("Tag", { fg = p.electric_blue })
    hi("Delimiter", { fg = p.cyber_orange })
    hi("SpecialComment", { fg = p.chrome_teal, italic = true })
    hi("Debug", { fg = p.synth_magenta })
    hi("Underlined", { underline = true })
    hi("Ignore", { fg = p.gunmetal })
    hi("Error", { fg = p.synth_magenta, bold = true })
    hi("Todo", { fg = p.void, bg = p.chrome_teal, bold = true })

    -- treesitter
    hi("@comment", { link = "Comment" })
    hi("@comment.documentation", { fg = p.slate_light, italic = sComm.italic, bold = sComm.bold })
    hi("@error", { link = "Error" })
    hi("@keyword", { fg = p.synth_magenta, italic = sKeyw.italic, bold = sKeyw.bold })
    hi("@keyword.function", { fg = p.synth_magenta, italic = sKeyw.italic, bold = sKeyw.bold })
    hi("@keyword.operator", { fg = p.cyber_orange, italic = sKeyw.italic, bold = sKeyw.bold })
    hi("@keyword.return", { fg = p.cyber_orange, italic = sKeyw.italic, bold = sKeyw.bold })
    hi("@keyword.import", { fg = p.violet_flux, italic = sKeyw.italic, bold = sKeyw.bold })
    hi("@keyword.conditional", { fg = p.cyber_orange, italic = sKeyw.italic, bold = sKeyw.bold })
    hi("@keyword.repeat", { fg = p.cyber_orange, italic = sKeyw.italic, bold = sKeyw.bold })
    hi("@keyword.exception", { fg = p.cyber_orange, italic = sKeyw.italic, bold = sKeyw.bold })
    hi("@keyword.modifier", { fg = p.cyber_orange, italic = sKeyw.italic, bold = sKeyw.bold })
    hi("@string", { fg = p.neon_pink })
    hi("@string.escape", { fg = p.aurum_gold })
    hi("@string.special", { fg = p.aurum_gold })
    hi("@string.regex", { fg = p.neon_pink })
    hi("@string.documentation", { fg = p.neon_pink, italic = true })
    hi("@number", { fg = p.aurum_gold })
    hi("@number.float", { fg = p.aurum_gold })
    hi("@boolean", { fg = p.cyber_orange, italic = sBool.italic, bold = sBool.bold })
    hi("@character", { fg = p.neon_pink })
    hi("@character.special", { fg = p.aurum_gold })
    hi("@function", { fg = p.neon_yellow, italic = sFn.italic, bold = sFn.bold })
    hi("@function.builtin", { fg = p.neon_yellow, italic = sFn.italic, bold = sFn.bold })
    hi("@function.call", { fg = p.neon_yellow, italic = sFn.italic, bold = sFn.bold })
    hi("@function.method", { fg = p.neon_yellow, italic = sFn.italic, bold = sFn.bold })
    hi("@function.method.call", { fg = p.neon_yellow, italic = sFn.italic, bold = sFn.bold })
    hi("@function.macro", { fg = p.matrix_green, italic = sFn.italic, bold = sFn.bold })
    hi("@constructor", { fg = p.chrome_teal })
    hi("@variable", { fg = p.slate_light, italic = sVar.italic, bold = sVar.bold })
    hi("@variable.builtin", { fg = p.synth_magenta, italic = sVar.italic, bold = sVar.bold })
    hi("@variable.parameter", { fg = p.matrix_green, italic = sVar.italic, bold = sVar.bold })
    hi("@variable.parameter.builtin", { fg = p.matrix_green, italic = sVar.italic, bold = sVar.bold })
    hi("@variable.member", { fg = p.synth_magenta, italic = sVar.italic, bold = sVar.bold })
    hi("@type", { fg = p.electric_blue })
    hi("@type.builtin", { fg = p.electric_blue })
    hi("@type.definition", { fg = p.chrome_teal })
    hi("@type.qualifier", { fg = p.cyber_orange })
    hi("@namespace", { fg = p.violet_flux })
    hi("@module", { fg = p.violet_flux })
    hi("@module.builtin", { fg = p.violet_flux })
    hi("@label", { fg = p.matrix_green })
    hi("@operator", { fg = p.cyber_orange })
    hi("@delimiter", { fg = p.cyber_orange })
    hi("@punctuation.bracket", { fg = p.cyber_orange })
    hi("@punctuation.delimiter", { fg = p.cyber_orange })
    hi("@punctuation.special", { fg = p.aurum_gold })
    hi("@attribute", { fg = p.aurum_gold })
    hi("@attribute.builtin", { fg = p.aurum_gold })
    hi("@constant", { fg = p.synth_magenta })
    hi("@constant.builtin", { fg = p.cyber_orange, bold = true })
    hi("@constant.macro", { fg = p.matrix_green })
    hi("@property", { fg = p.synth_magenta })
    hi("@field", { fg = p.synth_magenta })
    hi("@tag", { fg = p.hot_pink })
    hi("@tag.builtin", { fg = p.hot_pink })
    hi("@tag.attribute", { fg = p.aurum_gold })
    hi("@tag.delimiter", { fg = p.matrix_green })
    hi("@markup.heading", { fg = p.off_white, bold = true })
    hi("@markup.heading.1", { fg = p.electric_blue, bold = true })
    hi("@markup.heading.2", { fg = p.chrome_teal, bold = true })
    hi("@markup.heading.3", { fg = p.violet_flux, bold = true })
    hi("@markup.raw", { fg = p.matrix_green })
    hi("@markup.raw.block", { fg = p.matrix_green })
    hi("@markup.link", { fg = p.electric_blue, underline = true })
    hi("@markup.link.label", { fg = p.electric_blue })
    hi("@markup.link.url", { fg = p.chrome_teal, underline = true })
    hi("@markup.italic", { italic = true })
    hi("@markup.strong", { bold = true })
    hi("@markup.strikethrough", { strikethrough = true })
    hi("@markup.list", { fg = p.cyber_orange })
    hi("@markup.list.checked", { fg = p.signal_green })
    hi("@markup.list.unchecked", { fg = p.slate_light })
    hi("@markup.quote", { fg = p.slate_light, italic = true })
    hi("@markup.math", { fg = p.aurum_gold })
    hi("@markup.environment", { fg = p.violet_flux })
    hi("@diff.plus", { fg = p.signal_green })
    hi("@diff.minus", { fg = p.neon_pink })
    hi("@diff.delta", { fg = p.cyber_orange })

    -- lsp
    hi("@lsp.type.class", { fg = p.chrome_teal })
    hi("@lsp.type.struct", { fg = p.chrome_teal })
    hi("@lsp.type.enum", { fg = p.chrome_teal })
    hi("@lsp.type.interface", { fg = p.chrome_teal })
    hi("@lsp.type.typeParameter", { fg = p.chrome_teal })
    hi("@lsp.type.namespace", { fg = p.violet_flux })
    hi("@lsp.type.module", { fg = p.violet_flux })
    hi("@lsp.type.function", { fg = p.neon_yellow })
    hi("@lsp.type.method", { fg = p.neon_yellow })
    hi("@lsp.type.variable", { fg = p.slate_light })
    hi("@lsp.type.parameter", { fg = p.matrix_green })
    hi("@lsp.type.property", { fg = p.synth_magenta })
    hi("@lsp.type.enumMember", { fg = p.matrix_green })
    hi("@lsp.type.macro", { fg = p.matrix_green })
    hi("@lsp.type.keyword", { fg = p.synth_magenta })
    hi("@lsp.type.comment", { link = "Comment" })
    hi("@lsp.type.string", { fg = p.neon_pink })
    hi("@lsp.type.number", { fg = p.aurum_gold })
    hi("@lsp.type.operator", { fg = p.cyber_orange })
    hi("@lsp.type.decorator", { fg = p.aurum_gold })
    hi("@lsp.type.event", { fg = p.off_white })
    hi("@lsp.type.regexp", { fg = p.neon_pink })
    hi("@lsp.type.selfKeyword", { fg = p.synth_magenta })
    hi("@lsp.mod.deprecated", { strikethrough = true })
    hi("@lsp.mod.inactive", { fg = p.gunmetal })
    hi("DiagnosticError", { fg = p.synth_magenta })
    hi("DiagnosticWarn", { fg = p.cyber_orange })
    hi("DiagnosticInfo", { fg = p.electric_blue })
    hi("DiagnosticHint", { fg = p.chrome_teal })
    hi("DiagnosticOk", { fg = p.signal_green })
    hi("DiagnosticUnderlineError", { undercurl = true, sp = p.synth_magenta })
    hi("DiagnosticUnderlineWarn", { undercurl = true, sp = p.cyber_orange })
    hi("DiagnosticUnderlineInfo", { undercurl = true, sp = p.electric_blue })
    hi("DiagnosticUnderlineHint", { undercurl = true, sp = p.chrome_teal })
    hi("DiagnosticSignError", { fg = p.synth_magenta, bg = p.void })
    hi("DiagnosticSignWarn", { fg = p.cyber_orange, bg = p.void })
    hi("DiagnosticSignInfo", { fg = p.electric_blue, bg = p.void })
    hi("DiagnosticSignHint", { fg = p.chrome_teal, bg = p.void })
    hi("DiagnosticVirtualTextError", { fg = p.synth_magenta, bg = p.void, italic = true })
    hi("DiagnosticVirtualTextWarn", { fg = p.cyber_orange, bg = p.void, italic = true })
    hi("DiagnosticVirtualTextInfo", { fg = p.electric_blue, bg = p.void, italic = true })
    hi("DiagnosticVirtualTextHint", { fg = p.chrome_teal, bg = p.void, italic = true })
    hi("LspReferenceText", { bg = p.gunmetal })
    hi("LspReferenceRead", { bg = p.gunmetal })
    hi("LspReferenceWrite", { bg = p.gunmetal, underline = true })
    hi("LspCodeLens", { fg = p.electric_blue_dim, italic = true })
    hi("LspInlayHint", { fg = p.electric_blue_dim, bg = p.gunmetal, italic = true })
    hi("LspSignatureActiveParameter", { fg = p.electric_blue, bold = true })

    -- diff
    hi("DiffAdd", { fg = p.signal_green, bg = p.void })
    hi("DiffChange", { fg = p.cyber_orange, bg = p.void })
    hi("DiffDelete", { fg = p.neon_pink, bg = p.void })
    hi("DiffText", { fg = p.signal_green, bg = p.gunmetal })
    hi("diffAdded", { fg = p.signal_green })
    hi("diffRemoved", { fg = p.neon_pink })
    hi("diffChanged", { fg = p.cyber_orange })
    hi("diffFile", { fg = p.electric_blue })
    hi("diffNewFile", { fg = p.signal_green })
    hi("diffOldFile", { fg = p.neon_pink })
    hi("diffLine", { fg = p.violet_flux })
    hi("diffIndexLine", { fg = p.chrome_teal })

    -- todo-comments
    hi("TodoBgTODO", { fg = p.aurum_gold, bold = true })
    hi("TodoBgFIXME", { fg = p.aurum_gold, bold = true })
    hi("TodoBgNOTE", { fg = p.aurum_gold, bold = true })
    hi("TodoBgWARN", { fg = p.aurum_gold, bold = true })
    hi("TodoBgHACK", { fg = p.aurum_gold, bold = true })

    -- noice
    hi("NoiceCmdline", { fg = p.off_white, bg = p.gunmetal })
    hi("NoiceCmdlineIcon", { fg = p.electric_blue, bg = p.gunmetal })
    hi("NoiceCmdlineIconLua", { fg = p.electric_blue, bg = p.gunmetal })
    hi("NoiceCmdlineIconSearch", { fg = p.electric_blue, bg = p.gunmetal })
    hi("NoiceCmdlinePopup", { fg = p.slate_light, bg = p.gunmetal })
    hi("NoiceCmdlinePopupBorder", { fg = p.electric_blue_dim, bg = p.gunmetal })
    hi("NoiceCmdlinePopupBorderSearch", { fg = p.aurum_gold, bg = p.gunmetal })
    hi("NoiceCmdlinePopupBorderLua", { fg = p.electric_blue, bg = p.gunmetal })
    hi("NoiceCmdlinePopupBorderFilter", { fg = p.electric_blue_dim, bg = p.gunmetal })
    hi("NoiceCmdlinePopupBorderHelp", { fg = p.electric_blue_dim, bg = p.gunmetal })
    hi("NoiceCmdlinePopupBorderInput", { fg = p.electric_blue_dim, bg = p.gunmetal })
    hi("NoiceCmdlinePopupTitle", { fg = p.electric_blue, bg = p.gunmetal })
    hi("NoicePopup", { fg = p.slate_light, bg = p.gunmetal })
    hi("NoicePopupBorder", { fg = p.electric_blue_dim, bg = p.gunmetal })
    hi("NoiceMini", { fg = p.slate_light, bg = p.gunmetal })
    hi("NoiceConfirm", { fg = p.off_white, bg = p.gunmetal })
    hi("NoiceConfirmBorder", { fg = p.electric_blue_dim, bg = p.gunmetal })
    hi("NoiceLspProgressTitle", { fg = p.chrome_teal })
    hi("NoiceLspProgressClient", { fg = p.electric_blue_dim })
    hi("NoiceLspProgressSpinner", { fg = p.electric_blue })
    hi("NoiceFormatProgressDone", { fg = p.void, bg = p.electric_blue })
    hi("NoiceFormatProgressTodo", { fg = p.void, bg = p.gunmetal })

    -- bufferline
    hi("BufferLineFill", { bg = p.void})
    hi("BufferLineBufferSelected", { fg = p.electric_blue, bg = p.gunmetal, bold = true })
    hi("BufferLineBuffer", { fg = p.slate_light, bg = p.void })
    hi("BufferLineCloseButton", { fg = p.synth_magenta, bg = p.void })
    hi("BufferLineCloseButtonSelected", { fg = p.synth_magenta, bg = p.gunmetal })
    hi("BufferLineSeparator", { fg = p.slate_light, bg = p.void })
    hi("BufferLineIndicatorSelected", { fg = p.electric_blue, bg = p.gunmetal })
    hi("BufferLineModified", { fg = p.cyber_orange, bg = p.gunmetal })
    hi("BufferLineModifiedSelected", { fg = p.cyber_orange, bg = p.gunmetal })
    hi("BufferLineBackground", { fg = p.slate_light, bg = p.void})

    for group, attrs in pairs(cfg.options.overrides) do
        hi(group, attrs)
    end

end

return M
